baseURL = 'https://natasha-kamerkar2.github.io/'
languageCode = 'en-us'
title = 'Natasha'
theme = 'hugo-PaperMod'

[params]
    showToc = true
    TocOpen = false
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowCodeCopyButtons = true
    hideMeta = false
    [params.cover]
        hiddenInList = true
        hiddenInSingle = false
        responsiveImages = true
    [params.profileMode]
        enabled = true
        Title = "Hi there 👋"
        Subtitle = "Welcome"
        Content = ""
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/natasha-kamerkar2/"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/nutoo2/"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/natasha-kamerkar/"

[taxonomies]
    tag = "tags"
    series = "series"

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 30

[markup.goldmark.renderer]
    unsafe = true
