baseURL = 'https://john-doe.github.io/'
languageCode = 'en-us'
title = 'John'
theme = 'hugo-PaperMod'

[params]
    showToc = true
    TocOpen = false
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowCodeCopyButtons = true
    hideMeta = false
    [params.cover]
        hiddenInList = true
        hiddenInSingle = false
        responsiveImages = true
    [params.profileMode]
        enabled = true
        Title = "Hi there 👋"
        Subtitle = "Welcome to my blog"
        Content = ""
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/john-doe/"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/john-doe"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/john-doe/"

[taxonomies]
    tag = "tags"
    series = "series"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "series"
        name = "Series"
        url = "/series/"
        weight = 30
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 40
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 50
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 60


[markup.goldmark.renderer]
    unsafe = true
